# Site settings
title: Yet another PowerShell blog
email: xvorsx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rambling about .NET, software development, PowerShell and live.
  Seattle, WA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vors.github.io" # the base hostname & protocol for your site
twitter_username: xvorsx
github_username:  vors
author_name: "Sergei Vorobev"

# Build settings
markdown: kramdown

# Analytics
google_universal_analytics: UA-67557006-1
google_universal_analytics_cookiedomain: auto
